version: '3'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0    
    restart: always
    tty: true
    volumes:
      - ./node/mysql_db:/docker-entrypoint-initdb.d #SETUP
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root   
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 3   

  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    restart: always
    command: sh -c "npm install && node index.js"
    volumes:
      - ./node:/usr/src/app #Map Local files to container
    tty: true
    depends_on:
      db:
        condition: service_healthy  


  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on: 
     - app